export enum SlideActionTypes  {
    ADD_SLIDE = 'ADD_SLIDE',
    REMOVE_SLIDE = 'REMOVE_SLIDE',
    CHANGE_SLIDE_POSITION = 'CHANGE_SLIDE_POSITION',
    CHANGE_SLIDE_BACKGROUND = 'CHANGE_SLIDE_BACKGROUND',
    //create elements
    INSERT_FIGURE = 'INSERT_FIGURE',
    INSERT_IMAGE = 'INSERT_IMAGE',
    INSERT_TEXT_FIELD = 'INSERT_TEXT_FIELD',
    //change elements
    CHANGE_SLIDE_ELEM_POSITION = 'CHANGE_SLIDE_ELEM_POSITION',
    CHANGE_SLIDE_ELEM_SIZE = 'CHANGE_SLIDE_ELEM_SIZE',
    CHANGE_SLIDE_ELEM_FONT = 'CHANGE_SLIDE_ELEM_FONT',
    CHANGE_SLIDE_ELEM_TEXT_SIZE = 'CHANGE_SLIDE_ELEM_TEXT_SIZE',
    CHANGE_SLIDE_ELEM_TEXT = 'CHANGE_SLIDE_ELEM_TEXT',
    CHANGE_SLIDE_ELEM_COLOR = 'CHANGE_SLIDE_ELEM_COLOR',
}