export enum SlideActionTypes  {
    ADD_SLIDE = 'ADD_SLIDE', 
    REMOVE_SLIDE = 'REMOVE_SLIDE', 
    CHANGE_SLIDE_POSITION = 'CHANGE_SLIDE_POSITION', 
    CHANGE_SLIDE_BACKGROUND = 'CHANGE_SLIDE_BACKGROUND', 
    CHANGE_SLIDE_BACKGROUND_GRADIENT = 'CHANGE_SLIDE_BACKGROUND_GRADIENT',
    //create elements
    INSERT_FIGURE = 'INSERT_FIGURE', 
    INSERT_IMAGE = 'INSERT_IMAGE', 
    INSERT_TEXT_FIELD = 'INSERT_TEXT_FIELD', 
    //change elements
    REMOVE_ELEM = 'REMOVE_ELEM', 
    CHANGE_ELEM_POSITION = 'CHANGE_ELEM_POSITION',
    CHANGE_ELEM_SIZE = 'CHANGE_ELEM_SIZE', 
    CHANGE_TEXT_FONT = 'CHANGE_TEXT_FONT', 
    CHANGE_TEXT_SIZE = 'CHANGE_TEXT_SIZE',
    CHANGE_TEXT = 'CHANGE_TEXT', 
    CHANGE_ELEM_COLOR = 'CHANGE_ELEM_COLOR',
    CHANGE_TEXT_ALIGN = 'CHANGE_TEXT_ALIGN',
    UPDATE_SLIDES = 'UPDATE_SLIDES'
}